//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zacaz
    {
        public int IdZacaz { get; set; }
        public string FIO { get; set; }
        public string NameK { get; set; }
        public Nullable<int> IdK { get; set; }
        public Nullable<int> IdP { get; set; }
        public string DataVz { get; set; }
    
        public virtual Kniga Kniga { get; set; }
        public virtual People People { get; set; }
    }
}
